### ISSUE TITLE
Drowning 

### ISSUE THREAD

**Issue by Krglok** [CrystalCraftMC/CrystalSpace#11]
I tested the plugin with 1.8.3 Bukkit Server (Spigot)
Anything goes fine with world generation. I used a modified  empty ids.

But the drowning wil not function by default. Are there any config settings ?

Last year i made a 1.72 version and must make some source code changing to give drowning the correct function. 

I tested my old setup 
Ids setting:
    alwaysnight: true  //  correct function ready
    neutralmobs: false //  no correct function
    hostilemobs: false  //  no correct function
    weather: false  //  no correct function

P.S: I hope you do support this plugin , its awesome. My own update to 1.72 is not so good. I have no experience in world generation. And so i stop the fork.

Happy mining,
Krglok

**Comment by iffa** [comment]
You can find drowning configuration in config.yml:

https://github.com/CrystalCraftMC/CrystalSpace/blob/master/src/main/resources/config.yml#L26

As for the non-functioning settings, they are leftovers from **really old** code (2011), and they no longer function: you should use your world manager to handle mobs and weather (MultiVerse makes this easy)
