### ISSUE TITLE
Planet generator and new (>1.6?) blocks

### ISSUE THREAD

**Issue by iffa** [CrystalCraftMC/CrystalSpace#15]
As we all know in its current state the generator will not for some reason understand and put to use new Materials/blocks - we need to find out if it's our code's fault or if it is not an issue on our end.

I shall comment whatever I find out once I get everything up and running on my end.

**Comment by iffa** [comment]
New blocks do not work due to a limitation in the ChunkGenerator code itself:
https://hub.spigotmc.org/jira/browse/SPIGOT-121

New blocks no longer have these "magic values", and cannot be generated in the ChunkGenerator itself, so in order to generate them a populator would have to be used (which is really hard to implement in CrystalSpace).

**Comment by iffa** [comment]
Fixed with commit https://github.com/CrystalCraftMC/CrystalSpace/commit/d029868f46f2dce771e6286bec9dad7579020bc4

More testing + messing around needed to see if data values etc. work properly

**Comment by justwheel** [comment]
I plan to test this soon for clarification!
