### ISSUE TITLE
Create the schematics/ directory

### ISSUE THREAD

**Issue by justwheel** [CrystalCraftMC/CrystalSpace#2]
Currently, the plugin will not be able to start successfully, as in the `SpaceSchematicHandler` class, on line 92, there is a call to the `schematics/` directory to scan it and see if any schematics have been loaded into the server.

However, whatever code there once was to create this directory is gone, as it throws a NullPointerException whenever the line passes through.

Code is as follows:

`List<File> files = Arrays.asList(new File("plugins" + File.separator + "CrystalSpace" + File.separator + "schematics").listFiles());`

For now, I am hotfixing this by just manually creating the `schematics/` directory… this is lazy and is vital to be fixed before moving forward, but it requires more energy and rest to think about and read about than I currently have.

**Comment by iffa** [comment]
Code was just commented out for some reason, fix is included in #5

**Comment by justwheel** [comment]
Thanks for the fix! :)
