### ISSUE TITLE
Initialize a null array

### ISSUE THREAD

**Issue by justwheel** [CrystalCraftMC/CrystalSpace#3]
In `wgen/planets/PlanetsChunkGenerator.java`, on lines 121 and 131 (at time of posting), we create an empty ArrayList of data that doesn't seem to exist.

This data is supposed to be generated inside of the `ids.yml` file, and is referenced by the setting in `planets/planets.yml`, as `blocks.shells` and `blocks.cores`. However, the issue is that this data is not relayed into the declared ArrayLists on those lines.

Why is this data not being called? How is it not making it to the ArrayList?

The lines are as follows:
`ArrayList<MaterialData> list = new ArrayList<MaterialData>(curPl.shellBlkIds);`
`ArrayList<MaterialData> list = new ArrayList<MaterialData>(curPl.coreBlkIds);`

[Line 121 in Context](https://github.com/CrystalCraftMC/CrystalSpace/blob/master/src/main/java/com/crystalcraftmc/crystalspace/wgen/planets/PlanetsChunkGenerator.java#L121)
[Line 131 in Context](https://github.com/CrystalCraftMC/CrystalSpace/blob/master/src/main/java/com/crystalcraftmc/crystalspace/wgen/planets/PlanetsChunkGenerator.java#L131)

**Comment by iffa** [comment]
https://github.com/CrystalCraftMC/CrystalSpace/blob/master/src/main/resources/ids.yml

My bet would be that loading the default id's is not working for some reason, resulting in it loading in an empty list of emptiness => breaking the generation in horrible, horrible ways

Tried actually defining id's yourself and using them? I'm not sure as to what works with your fork currently and what does not, but I'd give it a shot! :)

**Comment by immaterial-ctrl** [comment]
@iffa  Awesome thanks for the tip! I don't believe id's have been defined by yet, though @jflory7  would know more, given he is the only one of our group who has started working with the plugin so far. Hopefullyonce my spring break starts this week, I'll be able to log some time in as well.

**Comment by iffa** [comment]
See my fix in #5 :)

**Comment by justwheel** [comment]
Confirmed fix. :)
